---
- hosts: DevOps
  vars:
    username: devops
    password: $6$5M4XNEwy$9HilmUk0dTotoF0yekmgRlrJtsFkKONZqvttZJVvFZIhRBjZp.cEgszH9QgyiAyzNlFJHMYjJQnCdaDhyKeW10
    path: /tmp/id_rsa
  gather_facts: no
  remote_user: ubuntu
  become: true

  tasks:
  - name: Add a new user named "{{ username }}"
    user:
      name: "{{ username }}"
      shell: /bin/bash
      password: "{{ password }}"
 
  - name: Add "{{ username }}" to the sudoers file
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "devops ALL=(ALL) NOPASSWD: ALL"
 
  - name: Generate SSH Key Pair
    community.crypto.openssh_keypair:
      path: "{{ path }}"

  - name: Deploy SSH Key
    authorized_key:
      user: devops
      key: "{{ lookup('file','/tmp/id_rsa.pub') }}"
      state: present
  - name: Disable Password Authentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: "PasswordAuthentication no"
      state: present
      backup: yes
  - name: Disable Root Login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes
    notify:
      - restart ssh
  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
